### ISSUE TITLE
Vanishing Inventory Bug

### ISSUE THREAD

**Issue by Landonian180** [VoidFlame/Issues#10]
Well, due to this bug you lose your entire inventory and exp levels. I have not done extensive testing on the issue because of my being extremely lazy but the issue only occurs after someone logs out in the nether dimension. My "Clan" so to speak has lost 2 sets of full diamond gear including tools and over 90 exp levels (We mine quartz to get exp and logged out in the nether), So getting this fixed means a great deal to the group. We'd like to get our gear back but if you cannot do that it's fine. Just get this fixed please and thanks -Lando

**Comment by kmecpp** [comment]
This should be fixed now
