### ISSUE TITLE
Galacticraft issues

### ISSUE THREAD

**Issue by donkeypoop** [VoidFlame/Issues#11]
This is a bug well sorta that many people are aware of. galacticraft is broken at least some things are. For example oxygen sealer, Oxygen collector, and oxygen compresser just to name a few. While it is still possible to go to space and build a space station i feel like there not much point as to keep supplied with oxygen you need to buy the ttanks from spawns as the only way to get oxygen is to have alot of electrolytic seperators and even then the oxygen distributer stops working after a while. To conclude i feel like some work needs to be done to the server as a whole; while i accept that it may not be as easy as that i feel like rubber voltz is understaffed and not kept up to date with bugs like that with galacticraft.

**Comment by donkeypoop** [comment]
I have currently experienced more problems with galacticraft and i wish to explain in more detail purely in aid of fixing the bug:
1)Oxygen sealers do not seal a space no matter the size they will take power just wont seal a room.
2)Oxygen collectors do not accept power from cables, or copper wires as of such do not work.
3)Oxygen compressors do not accept power from cables, or copper wires as of such do not work
4)Oxygen disputer(only way of obtaining oxygen that works without buying tanks from spawn) work to an extent the block can sometimes disappear as well as crash the players game at least in my experience
so far without further testing i could not find any other bugs. I will be more than happy to assist you in fixing this in any way.

**Comment by kmecpp** [comment]
I believe these should all be fixed now. Let me know if there are still any issues.
