### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by RubberSpark** [VoidFlame/Issues#26]
It is impossible to /f unclaim all since it says not enough command input it comes up saying you have to say /f unclaim all (Faction name) and that still does not work it just says unknown command and i literally moved base so i wanna claim it but i can't due to this stupid error.
![screenshot 192](https://user-images.githubusercontent.com/42364869/44330114-1cb05780-a45e-11e8-96c6-61c8751434fb.png)

**Comment by William191111** [comment]
RubberSpark you have to type out /f unclaim all all Factionname
