### ISSUE TITLE
Public or private space station list

### ISSUE THREAD

**Issue by kmecpp** [VoidFlame/Issues#27]
Based on this poll, about an equal number of people want space stations made private as made public.

https://www.strawpoll.me/16293580/r

To satisfy both groups of people, the best solution I see is to make space stations public by default and if people want to make them private, they may do so. However, at the cost of reducing the size from infinite to maybe something like 30x30 blocks

**Comment by jonsparks** [comment]
30x30 for private stations seems a bit too small. Maybe 250x250, even that's stretching it. Some people just want to enjoy the pack and not worry about raids

**Comment by kmecpp** [comment]
Space stations have all been merged into one world
