### ISSUE TITLE
Crashing bug

### ISSUE THREAD

**Issue by donkeypoop** [VoidFlame/Issues#32]
My friend ET0987654321 is experiencing crashing due to NEI we believe it to be this as it works fine in single player where he has disabled it and no longer crashes on the server when checking inventory this isnt a high priority has we have a temporary fix but would be nice if you could fix it at your earliest convenience both of us would be glad to support you in any way or answer any questions.

**Comment by kmecpp** [comment]
Can't fix anything without a crash report or log

**Comment by donkeypoop** [comment]
okay next time hes on ill get one thanks for the help

**Comment by donkeypoop** [comment]
[crash-2018-08-27_12.57.46-client.txt](https://github.com/VoidFlame/Issues/files/2336734/crash-2018-08-27_12.57.46-client.txt)
[crash-2018-08-27_12.59.20-client.txt](https://github.com/VoidFlame/Issues/files/2336735/crash-2018-08-27_12.59.20-client.txt)
[crash-2018-08-29_13.21.21-client.txt](https://github.com/VoidFlame/Issues/files/2336736/crash-2018-08-29_13.21.21-client.txt)

**Comment by donkeypoop** [comment]
There's three that i could get off him hopefully this shall help if any other assistance is required please let me know
.

**Comment by kmecpp** [comment]
Increasing the allocated RAM to at least 2GB should fix some of the issues. I will look into the other ones soon

**Comment by donkeypoop** [comment]
cheers

**Comment by kmecpp** [comment]
Most of these issues should be resolved in v0.7.0. If you experience any new crashes make a new issue
