### ISSUE TITLE
Small Galacticraft issue

### ISSUE THREAD

**Issue by donkeypoop** [VoidFlame/Issues#36]
Damn another galacticraft issue while only small and easy to get arround members (unsure about ranks) are unable to use the command /ssinvite <player> would leave to see a fix soon but its not a high priority as its only small

**Comment by donkeypoop** [comment]
it appears no galacticraft commands work as you cant even use /joinrace i am happy to provide assistance if required

**Comment by kmecpp** [comment]
This should be fixed now
