### ISSUE TITLE
RTP traps

### ISSUE THREAD

**Issue by Darmitor** [VoidFlame/Issues#48]
These need to be removed they're a giant pain and can happen any time you RTP actually caused me to quit the server until these are removed as I just get punished for trying to gather more resources.

**Comment by Darmitor** [comment]
It also causes the landscape to look ugly due to the massive explosions caused by them.

**Comment by RubberSpark** [comment]
I highly agree cause it stops new players from getting anywhere and it pretty much just drives them away and its bad for bussiness for the entire website and server and we want players to play the server and donate and help the server thrive just like the old voltz server did it lasted for 4 years.. So yeah this is a major issue that needs to be fixed and maybe put a protection over the areas just like spawn has a protection area.
