### ISSUE TITLE
PA Bug

### ISSUE THREAD

**Issue by FSUTylerR** [VoidFlame/Issues#54]
Helmet:     Elite Battery
                 Force Field
                Advanced Solar
Chestplate:Elite Battery
                 Force Field
                Standard Cooling System
Leggings: Elite Battery
                Force Field
                Sprint/Jump/Uphill Assist
               Kinetic Generator
Boots:      Elite Battery
                Force Field
                Shock Absorber
Fist:         Elite Battery
               Axe/Pickaxe/Shovel/Diamond Drill
              Melee Assist

Armor was charging fine until I installed the Dimensional Tear Generator then realized it was useless and uninstalled it but afterwards it continued to stay on my fist even tho the table said differently. Then my armor just kept draining its power.

**Comment by FSUTylerR** [comment]
Also the armor no longer creates heat

**Comment by kmecpp** [comment]
How exactly did you install the Dimensional Tear Generator?

**Comment by FSUTylerR** [comment]
Just like normal, through the PA tinker table

**Comment by FSUTylerR** [comment]
I uninstalled the kinetic gen and reinstalled it and it worked after, plus an admin swapped my bugged fist out for a different one
