### ISSUE TITLE
Applied Energistics redstone card on import buses not functioning correctly.

### ISSUE THREAD

**Issue by lalolalo9** [VoidFlame/Issues#58]
Place a redstone card on a ME import bus connected to a mekanism crusher.
Set a redstone signal by means of a ME level emitter. Set import bus to work with signal. Turn on signal. It will act as work with pulses.

**Comment by kmecpp** [comment]
What is the expected behavior and what does it actually do? Can you post screenshots or a video?

**Comment by lalolalo9** [comment]
Trying to recreate it but failed
