### ISSUE TITLE
s2 server digiminers and "gas" broken

### ISSUE THREAD

**Issue by 34486** [VoidFlame/Issues#59]
So apparently funnydog can't make hydrogen gas, and digiminers are not working at all. They consume power and do not mine anything at all when it is properly set up.

EDIT: I beleive it is because of the claim system, but i rtp and its still not the case unless the wild is still considered a claim by towny/baseclaim????? Maybe that is making it so it can't mine??

**Comment by Pugggyy** [comment]
Digi Miners are banned on S2

**Comment by kmecpp** [comment]
Fixed
