### ISSUE TITLE
AE2 Meteors dont spawn

### ISSUE THREAD

**Issue by PowerRanger2130** [VoidFlame/Issues#67]
I tried to find a meteor to start AE2, but there was none. I used /rtp many times, and where the meteor compass showed that there was a meteor, there was actually nothing. please fix this bug, i really want to start AE2.

**Comment by kmecpp** [comment]
This is on the official server?

**Comment by PowerRanger2130** [comment]
Yes. I have been searchinf for more than 2 hrs, and ive seen only 2.

**Comment by Breadabix** [comment]
They definitely spawn, im finding them while not looking for them. Try making a meteorite compass, should be able to find them pretty easily with that.
