### ISSUE TITLE
Configuartor Broken

### ISSUE THREAD

**Issue by Lunatic-Gamer** [VoidFlame/Issues#75]
Configurator: That item is not permitted in this area

Seems to be an issue from the update/restart done 11/08/2019 evening

**Comment by Lunatic-Gamer** [comment]
Supposedly the same with power fist?

**Comment by Lunatic-Gamer** [comment]
Super/Normal builders wand

**Comment by Breadabix** [comment]
Another thing not working is the builders wand and the super builders wand
