### ISSUE TITLE
Not Working 2nd Recipie Digital Miner

### ISSUE THREAD

**Issue by Fluttershyyaaay** [VoidFlame/Issues#81]
Two Recipies exits for the Digital Miner so far, tried the second one which 
is a mekanism shaped one which can be found on the wiki and ingame:
https://wiki.aidancbrady.com/wiki/Digital_Miner
upon crafting the Digital Miner appears and immediatley disappears in the crafting Menu when given the Items

**Comment by kmecpp** [comment]
Use the other recipe. That's intentionally disabled
