### ISSUE TITLE
Not in GZIP format crashing

### ISSUE THREAD

**Issue by sire411** [VoidFlame/Issues#86]
Each time I attempt to log in I'm greeted with a Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.ZipException Not in GZIP format, i'm not sure why.

Ingame name is CakeMaker656

**Comment by kmecpp** [comment]
What server? Raiding?

**Comment by kmecpp** [comment]
Hopefully this is fixed it latest modpack update with the bigger packets mod
