### ISSUE TITLE
Not Getting Crate Keys after rank Purches

### ISSUE THREAD

**Issue by zUn3nown** [VoidFlame/Issues#87]
Hello first of sorry for bad writing and english . 

I boughed the Gold rank and it says one of each crate key  but i didn't get them , also  a other player 
also didn't got ther Crate key's for buying the Legend rank

If ther is a way to fix that Pleas Try so.

**Comment by kmecpp** [comment]
Ping me on discord when you're on the server. Thanks for donating!
