### ISSUE TITLE
error dimension 29

### ISSUE THREAD

**Issue by Backszx** [VoidFlame/Issues#96]
![BUG](https://user-images.githubusercontent.com/63481847/79031357-9685df00-7b74-11ea-99c2-651b59c9765d.PNG)
I can't join the server, it just crashes the game and give this error, i tried with another account and it was okay, how can i solve it?

**Comment by kmecpp** [comment]
Is this on raiding or towny?

**Comment by kmecpp** [comment]
Finally fixed
