### ISSUE TITLE
Incorrect status for ME Fluid and Gas Busses

### ISSUE THREAD

**Issue by dfwdatacom** [VoidFlame/Issues#97]
Sub-server (raiding): Raiding

**Describe the bug**
The ME Fluid export bus and Gas import bus show "No channel available" and indicators are dark, but they still function. Not a problem, once i figured out they were actually working.

**To Reproduce**
Hook these buses to the me system.

**Expected behavior**

**Screenshots**

**Additional information**

**Comment by dfwdatacom** [comment]
Was working anyway, but showed online status after adding a p2p system.

**Comment by kmecpp** [comment]
Thanks for the suggestions. Can you put these on your suggestion site? https://suggestions.voidflame.com
