### ISSUE TITLE
Tutorial for FF & Interdiction needs modification

### ISSUE THREAD

**Issue by dfwdatacom** [VoidFlame/Issues#98]
Sub-server (raiding): Tutorial

**Describe the bug**
A forcefield surrounds the projector and everything else so you can't see how its configured. Suggest offsetting the FF above the equipment so you can right click and see how all of the modules are installed.  For the interdiction, install some modules so you can see how to set it up.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information**

**Comment by kmecpp** [comment]
Thanks for the suggestions. Can you put these on your suggestion site? https://suggestions.voidflame.com

**Comment by dfwdatacom** [comment]
Trying to reset my pw on voidflame, but not getting any emails. No spam filters.

 

Or junk@dfwdatacom.com <mailto:junk@dfwdatacom.com> 

 

 

John
