### ISSUE TITLE
Suggestion for the raiding server to prevent abuse.

### ISSUE THREAD

**Issue by dfwdatacom** [VoidFlame/Issues#99]
Sub-server (raiding/towny/etc): raiding

If you raid a base with an interdiction matrix and die, you should be restricted from using the /back command and all of your waypoints should be erased.  Prevents players from constantly doing /back to pick away at the defences. Helps players feel more secure.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information**

**Comment by kmecpp** [comment]
Thanks for the suggestions. Can you put these on your suggestion site? https://suggestions.voidflame.com
